# title: Minimal theme
# logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal

title: Abhishek Tomar
logo: /assets/img/logo.jpg
description: Research and Development | Senior Project Engineer at Centre for Development of Advanced Computing (Strategic Projects, Applied AI Group)




theme: jekyll-theme-minimal
