# title: Minimal theme
# logo: /assets/img/logo.png
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-minimal

title: <p align="center"> Abhishek Tomar </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/abtli/">LinkedIn</a> |
  <a href="https://github.com/abtGIT">GitHub</a>
  
  <br>   
  Research and Development | Senior Project Engineer at Centre for Development of Advanced Computing (Strategic Projects, Applied AI Group)
  <br>
  </p>



theme: jekyll-theme-minimal
